//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResCustomer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class addCustomerContact {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal addCustomerContact() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIS.Areas.Customers.Views.Customer.App_LocalResources.addCustomerContact", typeof(addCustomerContact).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gentile cliente,&lt;br /&gt;
        ///Ti ringraziamo per esserti registato sul nostro sito!
        ///Prima di poter utilizzare i servizi di Kaizen Indicator System è necessaria una ultima operazione: attivare il tuo account!&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;
        ///Per attivare il tuo account .
        /// </summary>
        public static string lblMail1 {
            get {
                return ResourceManager.GetString("lblMail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clicca qui.
        /// </summary>
        public static string lblMail2 {
            get {
                return ResourceManager.GetString("lblMail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;&lt;br /&gt;oppure copia e incolla il seguente link sulla barra di navigazione di un browser web: .
        /// </summary>
        public static string lblMail3 {
            get {
                return ResourceManager.GetString("lblMail3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br /&gt;&lt;br /&gt;&lt;br /&gt;Ti ricordiamo che tu sei il riferimento per la tua azienda, quindi ti consigliamo di tenere la password in un luogo segreto e sicuro.
        ///&lt;br /&gt;&lt;br /&gt;
        ///Nel caso in cui le credenziali di accesso fossero smarrite, contattare il nostro Servizio Clienti.
        ///&lt;br /&gt;&lt;br /&gt;
        ///Il Team di Kaizen Indicator System.
        /// </summary>
        public static string lblMail4 {
            get {
                return ResourceManager.GetString("lblMail4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrazione!.
        /// </summary>
        public static string lblSubject {
            get {
                return ResourceManager.GetString("lblSubject", resourceCulture);
            }
        }
    }
}
