//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResWebGemba {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ListTasksInExecution {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListTasksInExecution() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIS.Areas.Workplace.Views.WebGemba.App_LocalResources.ListTasksInExecution", typeof(ListTasksInExecution).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore generico. Non ne conosciamo le cause, sfortunatamente..
        /// </summary>
        public static string lblErrGeneric {
            get {
                return ResourceManager.GetString("lblErrGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore. Non è stato possibile completare il task perché alcuni parametri obbligatori non sono stati impostati..
        /// </summary>
        public static string lblErrParametersMissing {
            get {
                return ResourceManager.GetString("lblErrParametersMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore: non è possibile terminare questo task perchè qualche task precedente non è ancora terminato..
        /// </summary>
        public static string lblErrPreviousTasks {
            get {
                return ResourceManager.GetString("lblErrPreviousTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utente non autorizzato..
        /// </summary>
        public static string lblErrUserNotAuthorized {
            get {
                return ResourceManager.GetString("lblErrUserNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore: quantità non corretta. Verificare di aver inserito una quantità minore od uguale alla quantità prevista..
        /// </summary>
        public static string lblErrWrongQuantity {
            get {
                return ResourceManager.GetString("lblErrWrongQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string lblTHCustomerName {
            get {
                return ResourceManager.GetString("lblTHCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string lblTHNote {
            get {
                return ResourceManager.GetString("lblTHNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordine.
        /// </summary>
        public static string lblTHOrder {
            get {
                return ResourceManager.GetString("lblTHOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parametri.
        /// </summary>
        public static string lblTHParameters {
            get {
                return ResourceManager.GetString("lblTHParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prodotto.
        /// </summary>
        public static string lblTHProduct {
            get {
                return ResourceManager.GetString("lblTHProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome prodotto.
        /// </summary>
        public static string lblTHProductName {
            get {
                return ResourceManager.GetString("lblTHProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantità.
        /// </summary>
        public static string lblTHQuantity {
            get {
                return ResourceManager.GetString("lblTHQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task ID.
        /// </summary>
        public static string lblTHTaskID {
            get {
                return ResourceManager.GetString("lblTHTaskID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome task.
        /// </summary>
        public static string lblTHTaskName {
            get {
                return ResourceManager.GetString("lblTHTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segnalazione di un problema inviata con successo!.
        /// </summary>
        public static string lblWarningSent {
            get {
                return ResourceManager.GetString("lblWarningSent", resourceCulture);
            }
        }
    }
}
