//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResWebGemba {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WorkstationKPI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkstationKPI() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIS.Areas.Workplace.Views.WebGemba.App_LocalResources.WorkstationKPI", typeof(WorkstationKPI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ritardo medio settimana in corso.
        /// </summary>
        public static string lblCurrentDelay {
            get {
                return ResourceManager.GetString("lblCurrentDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lead time medio settimana in corso.
        /// </summary>
        public static string lblCurrentLeadTime {
            get {
                return ResourceManager.GetString("lblCurrentLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quantità prodotta settimana in corso.
        /// </summary>
        public static string lblCurrentQuantity {
            get {
                return ResourceManager.GetString("lblCurrentQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ore.
        /// </summary>
        public static string lblHours {
            get {
                return ResourceManager.GetString("lblHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ritardo medio settimana scorsa.
        /// </summary>
        public static string lblLastDelay {
            get {
                return ResourceManager.GetString("lblLastDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lead time medio settimana scorsa.
        /// </summary>
        public static string lblLastLeadTime {
            get {
                return ResourceManager.GetString("lblLastLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quantità prodotta settimana scorsa.
        /// </summary>
        public static string lblLastQuantity {
            get {
                return ResourceManager.GetString("lblLastQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ore manodopera unitaria settimana in corso.
        /// </summary>
        public static string lblUnitaryWorkingTimeCurrent {
            get {
                return ResourceManager.GetString("lblUnitaryWorkingTimeCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ore manodopera unitaria settimana scorsa.
        /// </summary>
        public static string lblUnitaryWorkingTimePast {
            get {
                return ResourceManager.GetString("lblUnitaryWorkingTimePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Variazione.
        /// </summary>
        public static string lblVariation {
            get {
                return ResourceManager.GetString("lblVariation", resourceCulture);
            }
        }
    }
}
