//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResWebGemba {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WorkstationKPI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkstationKPI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIS.Areas.Workplace.Views.WebGemba.App_LocalResources.WorkstationKPI", typeof(WorkstationKPI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ritardo medio settimana in corso.
        /// </summary>
        public static string lblCurrentDelay {
            get {
                return ResourceManager.GetString("lblCurrentDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead time medio settimana in corso.
        /// </summary>
        public static string lblCurrentLeadTime {
            get {
                return ResourceManager.GetString("lblCurrentLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantità prodotta settimana in corso.
        /// </summary>
        public static string lblCurrentQuantity {
            get {
                return ResourceManager.GetString("lblCurrentQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ore.
        /// </summary>
        public static string lblHours {
            get {
                return ResourceManager.GetString("lblHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ritardo medio settimana scorsa.
        /// </summary>
        public static string lblLastDelay {
            get {
                return ResourceManager.GetString("lblLastDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead time medio settimana scorsa.
        /// </summary>
        public static string lblLastLeadTime {
            get {
                return ResourceManager.GetString("lblLastLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantità prodotta settimana scorsa.
        /// </summary>
        public static string lblLastQuantity {
            get {
                return ResourceManager.GetString("lblLastQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ore manodopera unitaria settimana in corso.
        /// </summary>
        public static string lblUnitaryWorkingTimeCurrent {
            get {
                return ResourceManager.GetString("lblUnitaryWorkingTimeCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ore manodopera unitaria settimana scorsa.
        /// </summary>
        public static string lblUnitaryWorkingTimePast {
            get {
                return ResourceManager.GetString("lblUnitaryWorkingTimePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variazione.
        /// </summary>
        public static string lblVariation {
            get {
                return ResourceManager.GetString("lblVariation", resourceCulture);
            }
        }
    }
}
