//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResProcessMining {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIS.Areas.Analysis.Views.ProcessMining.App_LocalResources.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media dei tempi ciclo.
        /// </summary>
        public static string lblAverageCT {
            get {
                return ResourceManager.GetString("lblAverageCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scegli il prodotto:.
        /// </summary>
        public static string lblChooseProduct {
            get {
                return ResourceManager.GetString("lblChooseProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a product.
        /// </summary>
        public static string lblErrorSelectProduct {
            get {
                return ResourceManager.GetString("lblErrorSelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grafico delle frequenze.
        /// </summary>
        public static string lblFrequency {
            get {
                return ResourceManager.GetString("lblFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediana dei tempi ciclo.
        /// </summary>
        public static string lblMedianCT {
            get {
                return ResourceManager.GetString("lblMedianCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempi ciclo medi.
        /// </summary>
        public static string lblTitleAvgTC {
            get {
                return ResourceManager.GetString("lblTitleAvgTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequenza.
        /// </summary>
        public static string lblTitleFrequency {
            get {
                return ResourceManager.GetString("lblTitleFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mediana dei tempi ciclo.
        /// </summary>
        public static string lblTitleMedianTC {
            get {
                return ResourceManager.GetString("lblTitleMedianTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tempi ciclo totali (somma).
        /// </summary>
        public static string lblTitleTotalTC {
            get {
                return ResourceManager.GetString("lblTitleTotalTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totale dei tempi ciclo.
        /// </summary>
        public static string lblTotalCT {
            get {
                return ResourceManager.GetString("lblTotalCT", resourceCulture);
            }
        }
    }
}
