//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIS.Areas.Quality.Views.Home.App_LocalResources.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analisi per numero di non conformità.
        /// </summary>
        public static string lblAnalisiNumeroNC {
            get {
                return ResourceManager.GetString("lblAnalisiNumeroNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analisi dei costi delle non conformità.
        /// </summary>
        public static string lblAnalysisCost {
            get {
                return ResourceManager.GetString("lblAnalysisCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analisi dei costi delle categorie di non conformità.
        /// </summary>
        public static string lblAnalysisCostCategories {
            get {
                return ResourceManager.GetString("lblAnalysisCostCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analisi dei costi delle cause di non conformità.
        /// </summary>
        public static string lblAnalysisCostCauses {
            get {
                return ResourceManager.GetString("lblAnalysisCostCauses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analisi del rischio e delle non conformità.
        /// </summary>
        public static string lblAnalysisNCTitle {
            get {
                return ResourceManager.GetString("lblAnalysisNCTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analisi non conformità per prodotto.
        /// </summary>
        public static string lblAnalysisProduct {
            get {
                return ResourceManager.GetString("lblAnalysisProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cause di non conformità.
        /// </summary>
        public static string lblCause {
            get {
                return ResourceManager.GetString("lblCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azioni di miglioramento.
        /// </summary>
        public static string lblImprovementActions {
            get {
                return ResourceManager.GetString("lblImprovementActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stato di avanzamento delle azioni di miglioramento.
        /// </summary>
        public static string lblImprovementActionsProgressView {
            get {
                return ResourceManager.GetString("lblImprovementActionsProgressView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestione delle azioni di miglioramento.
        /// </summary>
        public static string lblManageImprovementActions {
            get {
                return ResourceManager.GetString("lblManageImprovementActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non conformità.
        /// </summary>
        public static string lblNonCompliances {
            get {
                return ResourceManager.GetString("lblNonCompliances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulo Qualità.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestione non conformità.
        /// </summary>
        public static string lblTitleNC {
            get {
                return ResourceManager.GetString("lblTitleNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorie di non conformità.
        /// </summary>
        public static string lblType {
            get {
                return ResourceManager.GetString("lblType", resourceCulture);
            }
        }
    }
}
