//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KISQualityEventsCheck.QualityModuleEvents {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QualityModuleEvents.QualityModuleEventsSoap")]
    public interface QualityModuleEventsSoap {
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento NotifyImprovementActionsDelaysResult dallo spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotifyImprovementActionsDelays", ReplyAction="*")]
        KISQualityEventsCheck.QualityModuleEvents.NotifyImprovementActionsDelaysResponse NotifyImprovementActionsDelays(KISQualityEventsCheck.QualityModuleEvents.NotifyImprovementActionsDelaysRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotifyImprovementActionsDelays", ReplyAction="*")]
        System.Threading.Tasks.Task<KISQualityEventsCheck.QualityModuleEvents.NotifyImprovementActionsDelaysResponse> NotifyImprovementActionsDelaysAsync(KISQualityEventsCheck.QualityModuleEvents.NotifyImprovementActionsDelaysRequest request);
        
        // CODEGEN: Generazione di un contratto di messaggio perché il nome di elemento NotifyCorrectiveActionsDelaysResult dallo spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotifyCorrectiveActionsDelays", ReplyAction="*")]
        KISQualityEventsCheck.QualityModuleEvents.NotifyCorrectiveActionsDelaysResponse NotifyCorrectiveActionsDelays(KISQualityEventsCheck.QualityModuleEvents.NotifyCorrectiveActionsDelaysRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NotifyCorrectiveActionsDelays", ReplyAction="*")]
        System.Threading.Tasks.Task<KISQualityEventsCheck.QualityModuleEvents.NotifyCorrectiveActionsDelaysResponse> NotifyCorrectiveActionsDelaysAsync(KISQualityEventsCheck.QualityModuleEvents.NotifyCorrectiveActionsDelaysRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotifyImprovementActionsDelaysRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NotifyImprovementActionsDelays", Namespace="http://tempuri.org/", Order=0)]
        public KISQualityEventsCheck.QualityModuleEvents.NotifyImprovementActionsDelaysRequestBody Body;
        
        public NotifyImprovementActionsDelaysRequest() {
        }
        
        public NotifyImprovementActionsDelaysRequest(KISQualityEventsCheck.QualityModuleEvents.NotifyImprovementActionsDelaysRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class NotifyImprovementActionsDelaysRequestBody {
        
        public NotifyImprovementActionsDelaysRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotifyImprovementActionsDelaysResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NotifyImprovementActionsDelaysResponse", Namespace="http://tempuri.org/", Order=0)]
        public KISQualityEventsCheck.QualityModuleEvents.NotifyImprovementActionsDelaysResponseBody Body;
        
        public NotifyImprovementActionsDelaysResponse() {
        }
        
        public NotifyImprovementActionsDelaysResponse(KISQualityEventsCheck.QualityModuleEvents.NotifyImprovementActionsDelaysResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NotifyImprovementActionsDelaysResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NotifyImprovementActionsDelaysResult;
        
        public NotifyImprovementActionsDelaysResponseBody() {
        }
        
        public NotifyImprovementActionsDelaysResponseBody(string NotifyImprovementActionsDelaysResult) {
            this.NotifyImprovementActionsDelaysResult = NotifyImprovementActionsDelaysResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotifyCorrectiveActionsDelaysRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NotifyCorrectiveActionsDelays", Namespace="http://tempuri.org/", Order=0)]
        public KISQualityEventsCheck.QualityModuleEvents.NotifyCorrectiveActionsDelaysRequestBody Body;
        
        public NotifyCorrectiveActionsDelaysRequest() {
        }
        
        public NotifyCorrectiveActionsDelaysRequest(KISQualityEventsCheck.QualityModuleEvents.NotifyCorrectiveActionsDelaysRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class NotifyCorrectiveActionsDelaysRequestBody {
        
        public NotifyCorrectiveActionsDelaysRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotifyCorrectiveActionsDelaysResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NotifyCorrectiveActionsDelaysResponse", Namespace="http://tempuri.org/", Order=0)]
        public KISQualityEventsCheck.QualityModuleEvents.NotifyCorrectiveActionsDelaysResponseBody Body;
        
        public NotifyCorrectiveActionsDelaysResponse() {
        }
        
        public NotifyCorrectiveActionsDelaysResponse(KISQualityEventsCheck.QualityModuleEvents.NotifyCorrectiveActionsDelaysResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class NotifyCorrectiveActionsDelaysResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NotifyCorrectiveActionsDelaysResult;
        
        public NotifyCorrectiveActionsDelaysResponseBody() {
        }
        
        public NotifyCorrectiveActionsDelaysResponseBody(string NotifyCorrectiveActionsDelaysResult) {
            this.NotifyCorrectiveActionsDelaysResult = NotifyCorrectiveActionsDelaysResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QualityModuleEventsSoapChannel : KISQualityEventsCheck.QualityModuleEvents.QualityModuleEventsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QualityModuleEventsSoapClient : System.ServiceModel.ClientBase<KISQualityEventsCheck.QualityModuleEvents.QualityModuleEventsSoap>, KISQualityEventsCheck.QualityModuleEvents.QualityModuleEventsSoap {
        
        public QualityModuleEventsSoapClient() {
        }
        
        public QualityModuleEventsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QualityModuleEventsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QualityModuleEventsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QualityModuleEventsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KISQualityEventsCheck.QualityModuleEvents.NotifyImprovementActionsDelaysResponse KISQualityEventsCheck.QualityModuleEvents.QualityModuleEventsSoap.NotifyImprovementActionsDelays(KISQualityEventsCheck.QualityModuleEvents.NotifyImprovementActionsDelaysRequest request) {
            return base.Channel.NotifyImprovementActionsDelays(request);
        }
        
        public string NotifyImprovementActionsDelays() {
            KISQualityEventsCheck.QualityModuleEvents.NotifyImprovementActionsDelaysRequest inValue = new KISQualityEventsCheck.QualityModuleEvents.NotifyImprovementActionsDelaysRequest();
            inValue.Body = new KISQualityEventsCheck.QualityModuleEvents.NotifyImprovementActionsDelaysRequestBody();
            KISQualityEventsCheck.QualityModuleEvents.NotifyImprovementActionsDelaysResponse retVal = ((KISQualityEventsCheck.QualityModuleEvents.QualityModuleEventsSoap)(this)).NotifyImprovementActionsDelays(inValue);
            return retVal.Body.NotifyImprovementActionsDelaysResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KISQualityEventsCheck.QualityModuleEvents.NotifyImprovementActionsDelaysResponse> KISQualityEventsCheck.QualityModuleEvents.QualityModuleEventsSoap.NotifyImprovementActionsDelaysAsync(KISQualityEventsCheck.QualityModuleEvents.NotifyImprovementActionsDelaysRequest request) {
            return base.Channel.NotifyImprovementActionsDelaysAsync(request);
        }
        
        public System.Threading.Tasks.Task<KISQualityEventsCheck.QualityModuleEvents.NotifyImprovementActionsDelaysResponse> NotifyImprovementActionsDelaysAsync() {
            KISQualityEventsCheck.QualityModuleEvents.NotifyImprovementActionsDelaysRequest inValue = new KISQualityEventsCheck.QualityModuleEvents.NotifyImprovementActionsDelaysRequest();
            inValue.Body = new KISQualityEventsCheck.QualityModuleEvents.NotifyImprovementActionsDelaysRequestBody();
            return ((KISQualityEventsCheck.QualityModuleEvents.QualityModuleEventsSoap)(this)).NotifyImprovementActionsDelaysAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        KISQualityEventsCheck.QualityModuleEvents.NotifyCorrectiveActionsDelaysResponse KISQualityEventsCheck.QualityModuleEvents.QualityModuleEventsSoap.NotifyCorrectiveActionsDelays(KISQualityEventsCheck.QualityModuleEvents.NotifyCorrectiveActionsDelaysRequest request) {
            return base.Channel.NotifyCorrectiveActionsDelays(request);
        }
        
        public string NotifyCorrectiveActionsDelays() {
            KISQualityEventsCheck.QualityModuleEvents.NotifyCorrectiveActionsDelaysRequest inValue = new KISQualityEventsCheck.QualityModuleEvents.NotifyCorrectiveActionsDelaysRequest();
            inValue.Body = new KISQualityEventsCheck.QualityModuleEvents.NotifyCorrectiveActionsDelaysRequestBody();
            KISQualityEventsCheck.QualityModuleEvents.NotifyCorrectiveActionsDelaysResponse retVal = ((KISQualityEventsCheck.QualityModuleEvents.QualityModuleEventsSoap)(this)).NotifyCorrectiveActionsDelays(inValue);
            return retVal.Body.NotifyCorrectiveActionsDelaysResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<KISQualityEventsCheck.QualityModuleEvents.NotifyCorrectiveActionsDelaysResponse> KISQualityEventsCheck.QualityModuleEvents.QualityModuleEventsSoap.NotifyCorrectiveActionsDelaysAsync(KISQualityEventsCheck.QualityModuleEvents.NotifyCorrectiveActionsDelaysRequest request) {
            return base.Channel.NotifyCorrectiveActionsDelaysAsync(request);
        }
        
        public System.Threading.Tasks.Task<KISQualityEventsCheck.QualityModuleEvents.NotifyCorrectiveActionsDelaysResponse> NotifyCorrectiveActionsDelaysAsync() {
            KISQualityEventsCheck.QualityModuleEvents.NotifyCorrectiveActionsDelaysRequest inValue = new KISQualityEventsCheck.QualityModuleEvents.NotifyCorrectiveActionsDelaysRequest();
            inValue.Body = new KISQualityEventsCheck.QualityModuleEvents.NotifyCorrectiveActionsDelaysRequestBody();
            return ((KISQualityEventsCheck.QualityModuleEvents.QualityModuleEventsSoap)(this)).NotifyCorrectiveActionsDelaysAsync(inValue);
        }
    }
}
