//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResAnalysis {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NCCostList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NCCostList() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIS.Areas.Quality.Views.NonCompliancesAnalysis.App_LocalResources.NCCostList", typeof(NCCostList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a €.
        /// </summary>
        public static string lblCurrency {
            get {
                return ResourceManager.GetString("lblCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data di fine.
        /// </summary>
        public static string lblDateEnd {
            get {
                return ResourceManager.GetString("lblDateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data di inizio.
        /// </summary>
        public static string lblDateStart {
            get {
                return ResourceManager.GetString("lblDateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: non hai il permesso di visualizzare questa pagina..
        /// </summary>
        public static string lblErrNoAuth {
            get {
                return ResourceManager.GetString("lblErrNoAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visualizzazione.
        /// </summary>
        public static string lblGraphFormat {
            get {
                return ResourceManager.GetString("lblGraphFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensile.
        /// </summary>
        public static string lblGraphFormatMonthly {
            get {
                return ResourceManager.GetString("lblGraphFormatMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settimanale.
        /// </summary>
        public static string lblGraphFormatWeekly {
            get {
                return ResourceManager.GetString("lblGraphFormatWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: le date inserite non sono corrette.
        /// </summary>
        public static string lblInputDateError {
            get {
                return ResourceManager.GetString("lblInputDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nessuna non conformità in questo periodo..
        /// </summary>
        public static string lblNoCauses {
            get {
                return ResourceManager.GetString("lblNoCauses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo.
        /// </summary>
        public static string lblTHCost {
            get {
                return ResourceManager.GetString("lblTHCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mese.
        /// </summary>
        public static string lblTHMonth {
            get {
                return ResourceManager.GetString("lblTHMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settimana.
        /// </summary>
        public static string lblTHWeek {
            get {
                return ResourceManager.GetString("lblTHWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo delle non conformità.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
    }
}
