//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResAnalysis {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NCCostList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NCCostList() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIS.Areas.Quality.Views.NonCompliancesAnalysis.App_LocalResources.NCCostList", typeof(NCCostList).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to €.
        /// </summary>
        public static string lblCurrency {
            get {
                return ResourceManager.GetString("lblCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data di fine.
        /// </summary>
        public static string lblDateEnd {
            get {
                return ResourceManager.GetString("lblDateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data di inizio.
        /// </summary>
        public static string lblDateStart {
            get {
                return ResourceManager.GetString("lblDateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore: non hai il permesso di visualizzare questa pagina..
        /// </summary>
        public static string lblErrNoAuth {
            get {
                return ResourceManager.GetString("lblErrNoAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizzazione.
        /// </summary>
        public static string lblGraphFormat {
            get {
                return ResourceManager.GetString("lblGraphFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensile.
        /// </summary>
        public static string lblGraphFormatMonthly {
            get {
                return ResourceManager.GetString("lblGraphFormatMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settimanale.
        /// </summary>
        public static string lblGraphFormatWeekly {
            get {
                return ResourceManager.GetString("lblGraphFormatWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore: le date inserite non sono corrette.
        /// </summary>
        public static string lblInputDateError {
            get {
                return ResourceManager.GetString("lblInputDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessuna non conformità in questo periodo..
        /// </summary>
        public static string lblNoCauses {
            get {
                return ResourceManager.GetString("lblNoCauses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo.
        /// </summary>
        public static string lblTHCost {
            get {
                return ResourceManager.GetString("lblTHCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mese.
        /// </summary>
        public static string lblTHMonth {
            get {
                return ResourceManager.GetString("lblTHMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settimana.
        /// </summary>
        public static string lblTHWeek {
            get {
                return ResourceManager.GetString("lblTHWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo delle non conformità.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
    }
}
