//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResAnalysis {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Number {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Number() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIS.Areas.Quality.Views.NonCompliancesAnalysis.App_LocalResources.Number", typeof(Number).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Analisi per numero di non conformità.
        /// </summary>
        public static string AnalysisNumTitle {
            get {
                return ResourceManager.GetString("AnalysisNumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data di fine analisi.
        /// </summary>
        public static string lblDateEnd {
            get {
                return ResourceManager.GetString("lblDateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data di inizio analisi.
        /// </summary>
        public static string lblDateStart {
            get {
                return ResourceManager.GetString("lblDateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visualizzazione.
        /// </summary>
        public static string lblGraphFormat {
            get {
                return ResourceManager.GetString("lblGraphFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensile.
        /// </summary>
        public static string lblGraphFormatMonthly {
            get {
                return ResourceManager.GetString("lblGraphFormatMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settimanale.
        /// </summary>
        public static string lblGraphFormatWeekly {
            get {
                return ResourceManager.GetString("lblGraphFormatWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: la data iniziale deve essere antecedente rispetto a quella finale.
        /// </summary>
        public static string lblInputDateError {
            get {
                return ResourceManager.GetString("lblInputDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pareto categorie di non conformità.
        /// </summary>
        public static string lblNCCategories {
            get {
                return ResourceManager.GetString("lblNCCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pareto cause di non conformità.
        /// </summary>
        public static string lblNCCause {
            get {
                return ResourceManager.GetString("lblNCCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Non conformità per mese.
        /// </summary>
        public static string lblNCMonth {
            get {
                return ResourceManager.GetString("lblNCMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Non conformità per settimana.
        /// </summary>
        public static string lblNCWeek {
            get {
                return ResourceManager.GetString("lblNCWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vedi dettagli.
        /// </summary>
        public static string lblViewDetails {
            get {
                return ResourceManager.GetString("lblViewDetails", resourceCulture);
            }
        }
    }
}
