//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResDepartmentAndonConfig {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GetDepartmentAndonConfig {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GetDepartmentAndonConfig() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIS.Areas.Andon.Views.DepartmentAndonConfig.App_LocalResources.GetDepartmentAndon" +
                            "Config", typeof(GetDepartmentAndonConfig).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore: utente non autorizzato..
        /// </summary>
        public static string lblNoAuth {
            get {
                return ResourceManager.GetString("lblNoAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrare pannello utenti.
        /// </summary>
        public static string lblShowActiveUsersActive {
            get {
                return ResourceManager.GetString("lblShowActiveUsersActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NON mostrare pannello utenti.
        /// </summary>
        public static string lblShowActiveUsersInactive {
            get {
                return ResourceManager.GetString("lblShowActiveUsersInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizzazione pannello utenti.
        /// </summary>
        public static string lblShowActiveUsersTitle {
            get {
                return ResourceManager.GetString("lblShowActiveUsersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizza solo il nome.
        /// </summary>
        public static string lblShowName {
            get {
                return ResourceManager.GetString("lblShowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mostrare indicatori di performance.
        /// </summary>
        public static string lblShowProductivityIndicatorsActive {
            get {
                return ResourceManager.GetString("lblShowProductivityIndicatorsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non mostrare indicatori di performance.
        /// </summary>
        public static string lblShowProductivityIndicatorsInactive {
            get {
                return ResourceManager.GetString("lblShowProductivityIndicatorsInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicatori di performance.
        /// </summary>
        public static string lblShowProductivityIndicatorsTitle {
            get {
                return ResourceManager.GetString("lblShowProductivityIndicatorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andon reparto: modalità di visualizzazione degli utenti nelle postazioni.
        /// </summary>
        public static string lblUsernameFormatTitle {
            get {
                return ResourceManager.GetString("lblUsernameFormatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizza il nome e l&apos;iniziale del cognome.
        /// </summary>
        public static string lblVisNombreYA {
            get {
                return ResourceManager.GetString("lblVisNombreYA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizza nome e cognome.
        /// </summary>
        public static string lblVisNombreYAppellido {
            get {
                return ResourceManager.GetString("lblVisNombreYAppellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizza solo lo username.
        /// </summary>
        public static string lblVisUsername {
            get {
                return ResourceManager.GetString("lblVisUsername", resourceCulture);
            }
        }
    }
}
