//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.34209
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.KISSchedulerWarning {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kis.org", ConfigurationName="KISSchedulerWarning.WarningSoap")]
    public interface WarningSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kis.org/Main", ReplyAction="*")]
        void Main();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WarningSoapChannel : ConsoleApplication1.KISSchedulerWarning.WarningSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WarningSoapClient : System.ServiceModel.ClientBase<ConsoleApplication1.KISSchedulerWarning.WarningSoap>, ConsoleApplication1.KISSchedulerWarning.WarningSoap {
        
        public WarningSoapClient() {
        }
        
        public WarningSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WarningSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WarningSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WarningSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Main() {
            base.Channel.Main();
        }
    }
}
