//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResProducts {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditTaskPanel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditTaskPanel() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIS.Areas.Products.Views.Products.App_LocalResources.EditTaskPanel", typeof(EditTaskPanel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestione categorie di parametro.
        /// </summary>
        public static string lblAltParamCategoryManagement {
            get {
                return ResourceManager.GetString("lblAltParamCategoryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tempo ciclo.
        /// </summary>
        public static string lblCTCycleTime {
            get {
                return ResourceManager.GetString("lblCTCycleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numero di operatori assegnati.
        /// </summary>
        public static string lblCTNumOps {
            get {
                return ResourceManager.GetString("lblCTNumOps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tempo di setup.
        /// </summary>
        public static string lblCTSetupTime {
            get {
                return ResourceManager.GetString("lblCTSetupTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Default.
        /// </summary>
        public static string lblDefault {
            get {
                return ResourceManager.GetString("lblDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attenzione: impossibile aggiungere il tempo ciclo. Verifica che non sia presente un altro tempo per il medesimo numero di operatori..
        /// </summary>
        public static string lblDetailEditError {
            get {
                return ResourceManager.GetString("lblDetailEditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aggiornamento avvenuto correttamente..
        /// </summary>
        public static string lblDetailEditSuccess {
            get {
                return ResourceManager.GetString("lblDetailEditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: esiste un task con lo stesso nome..
        /// </summary>
        public static string lblDetailEditTaskError {
            get {
                return ResourceManager.GetString("lblDetailEditTaskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Non sei autorizzato a visualizzare i parametri.
        /// </summary>
        public static string lblNoAuth {
            get {
                return ResourceManager.GetString("lblNoAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si è verificato un errore durante l&apos;aggiunta del parametro..
        /// </summary>
        public static string lblParamAddError {
            get {
                return ResourceManager.GetString("lblParamAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoria.
        /// </summary>
        public static string lblParamCategory {
            get {
                return ResourceManager.GetString("lblParamCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valore.
        /// </summary>
        public static string lblParamDescription {
            get {
                return ResourceManager.GetString("lblParamDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attenzione: selezionare una categoria.
        /// </summary>
        public static string lblParamErrCategory {
            get {
                return ResourceManager.GetString("lblParamErrCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attenzione: inserire un nome del parametro.
        /// </summary>
        public static string lblParamErrName {
            get {
                return ResourceManager.GetString("lblParamErrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valore fisso.
        /// </summary>
        public static string lblParamIsFixed {
            get {
                return ResourceManager.GetString("lblParamIsFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Obbligatorio.
        /// </summary>
        public static string lblParamIsRequired {
            get {
                return ResourceManager.GetString("lblParamIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nome.
        /// </summary>
        public static string lblParamName {
            get {
                return ResourceManager.GetString("lblParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descrizione.
        /// </summary>
        public static string lblTaskDescription {
            get {
                return ResourceManager.GetString("lblTaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nome.
        /// </summary>
        public static string lblTaskName {
            get {
                return ResourceManager.GetString("lblTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tempi di lavoro.
        /// </summary>
        public static string lblTitleCycleTimes {
            get {
                return ResourceManager.GetString("lblTitleCycleTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parametri.
        /// </summary>
        public static string lblTitleParameters {
            get {
                return ResourceManager.GetString("lblTitleParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore nei valori inseriti.
        /// </summary>
        public static string lblWorkingTimeWrong {
            get {
                return ResourceManager.GetString("lblWorkingTimeWrong", resourceCulture);
            }
        }
    }
}
