//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResTaskAnalysis {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TaskPanel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TaskPanel() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIS.Areas.Analysis.Views.TaskAnalysis.App_LocalResources.TaskPanel", typeof(TaskPanel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodo di riferimento.
        /// </summary>
        public static string lblChartSubTitle {
            get {
                return ResourceManager.GetString("lblChartSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Performance di produzione.
        /// </summary>
        public static string lblChartTitle {
            get {
                return ResourceManager.GetString("lblChartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ore di ritardo (somma).
        /// </summary>
        public static string lblDelays {
            get {
                return ResourceManager.GetString("lblDelays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data fine produzione.
        /// </summary>
        public static string lblEndProductionDate {
            get {
                return ResourceManager.GetString("lblEndProductionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodo di tempo.
        /// </summary>
        public static string lblGroupBy {
            get {
                return ResourceManager.GetString("lblGroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lead Time medio.
        /// </summary>
        public static string lblMeanLeadTime {
            get {
                return ResourceManager.GetString("lblMeanLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mese.
        /// </summary>
        public static string lblMonth {
            get {
                return ResourceManager.GetString("lblMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Giornaliero.
        /// </summary>
        public static string lblNone {
            get {
                return ResourceManager.GetString("lblNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Periodo.
        /// </summary>
        public static string lblPeriod {
            get {
                return ResourceManager.GetString("lblPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quantità di prodotti realizzati.
        /// </summary>
        public static string lblQuantity {
            get {
                return ResourceManager.GetString("lblQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nome task.
        /// </summary>
        public static string lblTaskName {
            get {
                return ResourceManager.GetString("lblTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Media ore di manodopera per unità di prodotto.
        /// </summary>
        public static string lblUnitaryWorkingTime {
            get {
                return ResourceManager.GetString("lblUnitaryWorkingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settimana.
        /// </summary>
        public static string lblWeek {
            get {
                return ResourceManager.GetString("lblWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ore di manodopera.
        /// </summary>
        public static string lblWorkingTime {
            get {
                return ResourceManager.GetString("lblWorkingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anno.
        /// </summary>
        public static string lblYear {
            get {
                return ResourceManager.GetString("lblYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prodotto.
        /// </summary>
        public static string ResProductName {
            get {
                return ResourceManager.GetString("ResProductName", resourceCulture);
            }
        }
    }
}
