//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResImprovementActions {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CorrectiveActionEdit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CorrectiveActionEdit() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIS.Areas.Quality.Views.ImprovementActions.App_LocalResources.CorrectiveActionEdi" +
                            "t", typeof(CorrectiveActionEdit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aggiungi un&apos;attività.
        /// </summary>
        public static string lblAddTask {
            get {
                return ResourceManager.GetString("lblAddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Task aggiunto con successo..
        /// </summary>
        public static string lblAddTaskOk {
            get {
                return ResourceManager.GetString("lblAddTaskOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chiusa.
        /// </summary>
        public static string lblClosed {
            get {
                return ResourceManager.GetString("lblClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descrizione.
        /// </summary>
        public static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data di fine lavoro prevista.
        /// </summary>
        public static string lblEndDate {
            get {
                return ResourceManager.GetString("lblEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attenzione: data non corretta. La data di fine prevista deve essere una data futura..
        /// </summary>
        public static string lblIncorrectDate {
            get {
                return ResourceManager.GetString("lblIncorrectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attenzione: nel campo &quot;giorni di lavoro previsti&quot; bisogna inserire un valore numerico intero positivo..
        /// </summary>
        public static string lblIncorrectLeadTime {
            get {
                return ResourceManager.GetString("lblIncorrectLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Giorni di lavoro previsti.
        /// </summary>
        public static string lblLeadTime {
            get {
                return ResourceManager.GetString("lblLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Non hai il permesso di visualizzare questa azione correttiva.
        /// </summary>
        public static string lblNotLoggedIn {
            get {
                return ResourceManager.GetString("lblNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aperta.
        /// </summary>
        public static string lblOpen {
            get {
                return ResourceManager.GetString("lblOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In esecuzione.
        /// </summary>
        public static string lblRunning {
            get {
                return ResourceManager.GetString("lblRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attività.
        /// </summary>
        public static string lblTaskTitle {
            get {
                return ResourceManager.GetString("lblTaskTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Team.
        /// </summary>
        public static string lblTeam {
            get {
                return ResourceManager.GetString("lblTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esecutore.
        /// </summary>
        public static string lblTeamExecutioner {
            get {
                return ResourceManager.GetString("lblTeamExecutioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aiutante.
        /// </summary>
        public static string lblTeamHelper {
            get {
                return ResourceManager.GetString("lblTeamHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modifica azione correttiva.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aggiornamento avvenuto con successo..
        /// </summary>
        public static string lblUpdateOk {
            get {
                return ResourceManager.GetString("lblUpdateOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documenti.
        /// </summary>
        public static string lblUploadDocument {
            get {
                return ResourceManager.GetString("lblUploadDocument", resourceCulture);
            }
        }
    }
}
