//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResImprovementActions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ImprovementActionProgressAndon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImprovementActionProgressAndon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIS.Areas.Quality.Views.ImprovementActions.App_LocalResources.ImprovementActionPr" +
                            "ogressAndon", typeof(ImprovementActionProgressAndon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiusa.
        /// </summary>
        public static string lblClosed {
            get {
                return ResourceManager.GetString("lblClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In esecuzione.
        /// </summary>
        public static string lblExecuting {
            get {
                return ResourceManager.GetString("lblExecuting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessuna azione di miglioramento di tuo interesse in corso..
        /// </summary>
        public static string lblNoDataFound {
            get {
                return ResourceManager.GetString("lblNoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperta.
        /// </summary>
        public static string lblOpen {
            get {
                return ResourceManager.GetString("lblOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrizione azione correttiva.
        /// </summary>
        public static string lblTHcActDescription {
            get {
                return ResourceManager.GetString("lblTHcActDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID azione correttiva.
        /// </summary>
        public static string lblTHcActID {
            get {
                return ResourceManager.GetString("lblTHcActID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead time previsto.
        /// </summary>
        public static string lblTHcActLeadTimeExpected {
            get {
                return ResourceManager.GetString("lblTHcActLeadTimeExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lblTHcActStatus {
            get {
                return ResourceManager.GetString("lblTHcActStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situazione attuale.
        /// </summary>
        public static string lblTHCurrentSituation {
            get {
                return ResourceManager.GetString("lblTHCurrentSituation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data di inizio prevista.
        /// </summary>
        public static string lblTHEarlyStart {
            get {
                return ResourceManager.GetString("lblTHEarlyStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risultati attesi.
        /// </summary>
        public static string lblTHExpectedResults {
            get {
                return ResourceManager.GetString("lblTHExpectedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data di fine prevista.
        /// </summary>
        public static string lblTHiActEndDateExpected {
            get {
                return ResourceManager.GetString("lblTHiActEndDateExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID azione di miglioramento.
        /// </summary>
        public static string lblTHiActID {
            get {
                return ResourceManager.GetString("lblTHiActID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data di fine prevista.
        /// </summary>
        public static string lblTHLateFinish {
            get {
                return ResourceManager.GetString("lblTHLateFinish", resourceCulture);
            }
        }
    }
}
