//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResImprovementActions {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Update {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Update() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIS.Areas.Quality.Views.ImprovementActions.App_LocalResources.Update", typeof(Update).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleziona un utente.
        /// </summary>
        public static string ddlUserSelect {
            get {
                return ResourceManager.GetString("ddlUserSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aggiungi un&apos;azione correttiva.
        /// </summary>
        public static string lblAddCorrectiveAction {
            get {
                return ResourceManager.GetString("lblAddCorrectiveAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chiuso.
        /// </summary>
        public static string lblClosed {
            get {
                return ResourceManager.GetString("lblClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data di chiusura prevista.
        /// </summary>
        public static string lblClosureDatePlanned {
            get {
                return ResourceManager.GetString("lblClosureDatePlanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data di chiusura reale.
        /// </summary>
        public static string lblClosureDateReal {
            get {
                return ResourceManager.GetString("lblClosureDateReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Note di chiusura.
        /// </summary>
        public static string lblClosureNotes {
            get {
                return ResourceManager.GetString("lblClosureNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Azioni correttive.
        /// </summary>
        public static string lblCorrectiveActions {
            get {
                return ResourceManager.GetString("lblCorrectiveActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creato da.
        /// </summary>
        public static string lblCreatedBy {
            get {
                return ResourceManager.GetString("lblCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Situazione attuale.
        /// </summary>
        public static string lblCurrentSituation {
            get {
                return ResourceManager.GetString("lblCurrentSituation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documenti.
        /// </summary>
        public static string lblDocuments {
            get {
                return ResourceManager.GetString("lblDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: azione di miglioramento non trovata..
        /// </summary>
        public static string lblErrIActNotFound {
            get {
                return ResourceManager.GetString("lblErrIActNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Non hai il permesso di visualizzare questa pagina.
        /// </summary>
        public static string lblErrNotLoggedIn {
            get {
                return ResourceManager.GetString("lblErrNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: non posso chiudere l&apos;azione di miglioramento perchè ci sono alcune azioni correttive aperte..
        /// </summary>
        public static string lblErrorClosure {
            get {
                return ResourceManager.GetString("lblErrorClosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Risultato atteso.
        /// </summary>
        public static string lblExpectedResult {
            get {
                return ResourceManager.GetString("lblExpectedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ultima modifica effettuata da.
        /// </summary>
        public static string lblModifedBy {
            get {
                return ResourceManager.GetString("lblModifedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data ultima modifica.
        /// </summary>
        public static string lblModifiedDate {
            get {
                return ResourceManager.GetString("lblModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aperto.
        /// </summary>
        public static string lblOpen {
            get {
                return ResourceManager.GetString("lblOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cause radice.
        /// </summary>
        public static string lblRootCauses {
            get {
                return ResourceManager.GetString("lblRootCauses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Status.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestione team.
        /// </summary>
        public static string lblTeam {
            get {
                return ResourceManager.GetString("lblTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manager.
        /// </summary>
        public static string lblTeamManager {
            get {
                return ResourceManager.GetString("lblTeamManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Team member.
        /// </summary>
        public static string lblTeamMember {
            get {
                return ResourceManager.GetString("lblTeamMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modifica attività di miglioramento.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modifiche effettuate con successo.
        /// </summary>
        public static string lblUpdateOk {
            get {
                return ResourceManager.GetString("lblUpdateOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carica il file.
        /// </summary>
        public static string lblUpload {
            get {
                return ResourceManager.GetString("lblUpload", resourceCulture);
            }
        }
    }
}
