//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResProductionHistory {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIS.Areas.Analysis.Views.ProductionHistory.App_LocalResources.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analisi.
        /// </summary>
        public static string lblAnalisis {
            get {
                return ResourceManager.GetString("lblAnalisis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per effettuare il login con un utente abilitato clicca qui.
        /// </summary>
        public static string lblClickHere {
            get {
                return ResourceManager.GetString("lblClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clienti.
        /// </summary>
        public static string lblCustomers {
            get {
                return ResourceManager.GetString("lblCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reparti.
        /// </summary>
        public static string lblDepartments {
            get {
                return ResourceManager.GetString("lblDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine periodo.
        /// </summary>
        public static string lblEndDate {
            get {
                return ResourceManager.GetString("lblEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data di termine produzione.
        /// </summary>
        public static string lblEndProductionDate {
            get {
                return ResourceManager.GetString("lblEndProductionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Riesuma il prodotto.
        /// </summary>
        public static string lblExhumate {
            get {
                return ResourceManager.GetString("lblExhumate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtra la selezione.
        /// </summary>
        public static string lblFilterSelection {
            get {
                return ResourceManager.GetString("lblFilterSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unità di misura.
        /// </summary>
        public static string lblMeasurementUnit {
            get {
                return ResourceManager.GetString("lblMeasurementUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleziona tutto.
        /// </summary>
        public static string lblSelectAll {
            get {
                return ResourceManager.GetString("lblSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizza ordini di produzione.
        /// </summary>
        public static string lblShowProductionOrder {
            get {
                return ResourceManager.GetString("lblShowProductionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualizza ordini di vendita.
        /// </summary>
        public static string lblShowSalesOrders {
            get {
                return ResourceManager.GetString("lblShowSalesOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formato visualizzazione.
        /// </summary>
        public static string lblShowSalesOrProductionOrders {
            get {
                return ResourceManager.GetString("lblShowSalesOrProductionOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inizio periodo.
        /// </summary>
        public static string lblStartDate {
            get {
                return ResourceManager.GetString("lblStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazione.
        /// </summary>
        public static string lblTHCustomerCountry {
            get {
                return ResourceManager.GetString("lblTHCustomerCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente.
        /// </summary>
        public static string lblTHCustomerName {
            get {
                return ResourceManager.GetString("lblTHCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regione.
        /// </summary>
        public static string lblTHCustomerProvince {
            get {
                return ResourceManager.GetString("lblTHCustomerProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reparto.
        /// </summary>
        public static string lblTHDepartment {
            get {
                return ResourceManager.GetString("lblTHDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fine produzione reale.
        /// </summary>
        public static string lblTHEndProductionDateReal {
            get {
                return ResourceManager.GetString("lblTHEndProductionDateReal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice prodotto.
        /// </summary>
        public static string lblTHProductExternalID {
            get {
                return ResourceManager.GetString("lblTHProductExternalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordine di produzione.
        /// </summary>
        public static string lblTHProductionOrderID {
            get {
                return ResourceManager.GetString("lblTHProductionOrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo di prodotto.
        /// </summary>
        public static string lblTHProductName {
            get {
                return ResourceManager.GetString("lblTHProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantità ordinata.
        /// </summary>
        public static string lblTHQuantityOrdered {
            get {
                return ResourceManager.GetString("lblTHQuantityOrdered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantità prodotta.
        /// </summary>
        public static string lblTHQuantityProduced {
            get {
                return ResourceManager.GetString("lblTHQuantityProduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ritardo (ore).
        /// </summary>
        public static string lblTHRealDelay {
            get {
                return ResourceManager.GetString("lblTHRealDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead time reale (ore).
        /// </summary>
        public static string lblTHRealLeadTime {
            get {
                return ResourceManager.GetString("lblTHRealLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ore di lavoro impiegate.
        /// </summary>
        public static string lblTHRealWorkingTime {
            get {
                return ResourceManager.GetString("lblTHRealWorkingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordine di vendita.
        /// </summary>
        public static string lblTHSalesOrderID {
            get {
                return ResourceManager.GetString("lblTHSalesOrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note ordine.
        /// </summary>
        public static string lblTHSalesOrderNotes {
            get {
                return ResourceManager.GetString("lblTHSalesOrderNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero di serie.
        /// </summary>
        public static string lblTHSerialNumber {
            get {
                return ResourceManager.GetString("lblTHSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storico Produzione.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipi di prodotto.
        /// </summary>
        public static string lblTypesOfProducts {
            get {
                return ResourceManager.GetString("lblTypesOfProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utente non autorizzato..
        /// </summary>
        public static string lblUserNotAuthorized {
            get {
                return ResourceManager.GetString("lblUserNotAuthorized", resourceCulture);
            }
        }
    }
}
