//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.34209
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.KISScheduler {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kis.org", ConfigurationName="KISScheduler.RitardiSoap")]
    public interface RitardiSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kis.org/Main", ReplyAction="*")]
        void Main();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RitardiSoapChannel : ConsoleApplication1.KISScheduler.RitardiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RitardiSoapClient : System.ServiceModel.ClientBase<ConsoleApplication1.KISScheduler.RitardiSoap>, ConsoleApplication1.KISScheduler.RitardiSoap {
        
        public RitardiSoapClient() {
        }
        
        public RitardiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RitardiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RitardiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RitardiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Main() {
            base.Channel.Main();
        }
    }
}
