//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResListOrderProduct {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ListOrderProduct {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListOrderProduct() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIS.Areas.SalesOrders.Views.SalesOrder.App_LocalResources.ListOrderProduct", typeof(ListOrderProduct).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero operatori previsti.
        /// </summary>
        public static string lblBNumOp {
            get {
                return ResourceManager.GetString("lblBNumOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postazione.
        /// </summary>
        public static string lblBPostazione {
            get {
                return ResourceManager.GetString("lblBPostazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantità.
        /// </summary>
        public static string lblBQuantita {
            get {
                return ResourceManager.GetString("lblBQuantita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termina forzatamente il prodotto.
        /// </summary>
        public static string lblCompleteProductBruteForce {
            get {
                return ResourceManager.GetString("lblCompleteProductBruteForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attenzione: il prodotto verra&apos; terminato forzatamente ed i suoi task non saranno piu&apos; disponibili nel WebGemba. Vuoi continuare?.
        /// </summary>
        public static string lblConfirmCompleteBruteForce {
            get {
                return ResourceManager.GetString("lblConfirmCompleteBruteForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data di consegna.
        /// </summary>
        public static string lblDataConsegna {
            get {
                return ResourceManager.GetString("lblDataConsegna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore: la data di fine produzione non può essere posteriore alla data di consegna..
        /// </summary>
        public static string lblDateError1 {
            get {
                return ResourceManager.GetString("lblDateError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore: la data di fine produzione non può essere nel passato..
        /// </summary>
        public static string lblDateError2 {
            get {
                return ResourceManager.GetString("lblDateError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore: data di consegna non valida..
        /// </summary>
        public static string lblDateError3 {
            get {
                return ResourceManager.GetString("lblDateError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data di consegna.
        /// </summary>
        public static string lblDeliveryDate {
            get {
                return ResourceManager.GetString("lblDeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reparto.
        /// </summary>
        public static string lblDepartment {
            get {
                return ResourceManager.GetString("lblDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiche realizzate con successo!.
        /// </summary>
        public static string lblDialogEditOk {
            get {
                return ResourceManager.GetString("lblDialogEditOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmazione cambiata con successo!.
        /// </summary>
        public static string lblDialogReplanOk {
            get {
                return ResourceManager.GetString("lblDialogReplanOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data fine produzione.
        /// </summary>
        public static string lblEndProductionDate {
            get {
                return ResourceManager.GetString("lblEndProductionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore: Quantità non valida..
        /// </summary>
        public static string lblErrInvalidQuantity {
            get {
                return ResourceManager.GetString("lblErrInvalidQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore: non c&apos;è tempo a sufficienza per produrre rispettando la data di fine produzione richiesta. Per favore, cambiare la data di fine produzione..
        /// </summary>
        public static string lblErrorEndProductionDate {
            get {
                return ResourceManager.GetString("lblErrorEndProductionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore: configurazione del prodotto non corretta..
        /// </summary>
        public static string lblErrorInProductCfg {
            get {
                return ResourceManager.GetString("lblErrorInProductCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore: il prodotto è già stato pianificato in produzione..
        /// </summary>
        public static string lblErrorStatus {
            get {
                return ResourceManager.GetString("lblErrorStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminato.
        /// </summary>
        public static string lblF {
            get {
                return ResourceManager.GetString("lblF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore generico..
        /// </summary>
        public static string lblGenericError {
            get {
                return ResourceManager.GetString("lblGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In esecuzione.
        /// </summary>
        public static string lblI {
            get {
                return ResourceManager.GetString("lblI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore nei dati di input..
        /// </summary>
        public static string lblInputError {
            get {
                return ResourceManager.GetString("lblInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestisci operatori assegnati ai task.
        /// </summary>
        public static string lblManageOperators {
            get {
                return ResourceManager.GetString("lblManageOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambia pianificazione dei task.
        /// </summary>
        public static string lblManageTasks {
            get {
                return ResourceManager.GetString("lblManageTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non pianificato.
        /// </summary>
        public static string lblN {
            get {
                return ResourceManager.GetString("lblN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordine.
        /// </summary>
        public static string lblOrdine {
            get {
                return ResourceManager.GetString("lblOrdine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non iniziato.
        /// </summary>
        public static string lblP {
            get {
                return ResourceManager.GetString("lblP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINE.
        /// </summary>
        public static string lblPFine {
            get {
                return ResourceManager.GetString("lblPFine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INIZIO.
        /// </summary>
        public static string lblPInizio {
            get {
                return ResourceManager.GetString("lblPInizio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string lblPNote {
            get {
                return ResourceManager.GetString("lblPNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAUSA.
        /// </summary>
        public static string lblPPausa {
            get {
                return ResourceManager.GetString("lblPPausa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROBLEMA.
        /// </summary>
        public static string lblPProblema {
            get {
                return ResourceManager.GetString("lblPProblema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prodotto completato con successo.
        /// </summary>
        public static string lblProductCompletedOk {
            get {
                return ResourceManager.GetString("lblProductCompletedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Prodotto.
        /// </summary>
        public static string lblProductID {
            get {
                return ResourceManager.GetString("lblProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prodotto.
        /// </summary>
        public static string lblProductName {
            get {
                return ResourceManager.GetString("lblProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore: prodotto non trovato.
        /// </summary>
        public static string lblProductNotFound {
            get {
                return ResourceManager.GetString("lblProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stato avanzamento prodotto.
        /// </summary>
        public static string lblProductStatus {
            get {
                return ResourceManager.GetString("lblProductStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATO PRODOTTO.
        /// </summary>
        public static string lblPStatoProdotto {
            get {
                return ResourceManager.GetString("lblPStatoProdotto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantità.
        /// </summary>
        public static string lblQuantity {
            get {
                return ResourceManager.GetString("lblQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produttività.
        /// </summary>
        public static string lblTHProductivity {
            get {
                return ResourceManager.GetString("lblTHProductivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manodopera reale (ore).
        /// </summary>
        public static string lblTHRealLabour {
            get {
                return ResourceManager.GetString("lblTHRealLabour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lblTHStatus {
            get {
                return ResourceManager.GetString("lblTHStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancella la riga d&apos;ordine.
        /// </summary>
        public static string lblTTDelete {
            get {
                return ResourceManager.GetString("lblTTDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lancia il prodotto in produzione.
        /// </summary>
        public static string lblTTPlan {
            get {
                return ResourceManager.GetString("lblTTPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa barcode su fogli multiple.
        /// </summary>
        public static string lblTTPrintBarcode {
            get {
                return ResourceManager.GetString("lblTTPrintBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa barcode su foglio singolo A4.
        /// </summary>
        public static string lblTTPrintSingleBarcode {
            get {
                return ResourceManager.GetString("lblTTPrintSingleBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stampa barcode su foglio singolo A3.
        /// </summary>
        public static string lblTTPrintSingleBarcodeA3 {
            get {
                return ResourceManager.GetString("lblTTPrintSingleBarcodeA3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambia la programmazione della produzione.
        /// </summary>
        public static string lblTTReprogram {
            get {
                return ResourceManager.GetString("lblTTReprogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salva i cambiamenti di quantità e data di consegna.
        /// </summary>
        public static string lblTTSave {
            get {
                return ResourceManager.GetString("lblTTSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rimuovi la pianificazione della produzione del prodotto.
        /// </summary>
        public static string lblTTUndo {
            get {
                return ResourceManager.GetString("lblTTUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utente non autorizzato..
        /// </summary>
        public static string lblUserNotAuthorized {
            get {
                return ResourceManager.GetString("lblUserNotAuthorized", resourceCulture);
            }
        }
    }
}
