//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResProducts {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIS.Areas.Products.Views.ProductParametersCategories.App_LocalResources.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aggiungi una nuova categoria.
        /// </summary>
        public static string lblAddCategory {
            get {
                return ResourceManager.GetString("lblAddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sei sicuro di voler cancellare questa categoria di parametro?.
        /// </summary>
        public static string lblConfirmDelete {
            get {
                return ResourceManager.GetString("lblConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attenzione: è avvenuto un errore durante la modifica dei dati..
        /// </summary>
        public static string lblEditError {
            get {
                return ResourceManager.GetString("lblEditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attenzione: è avvenuto un errore durante la cancellazione..
        /// </summary>
        public static string lblErrorDelete {
            get {
                return ResourceManager.GetString("lblErrorDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parametri.
        /// </summary>
        public static string lblNavParameters {
            get {
                return ResourceManager.GetString("lblNavParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categorie.
        /// </summary>
        public static string lblNavParametersCategories {
            get {
                return ResourceManager.GetString("lblNavParametersCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prodotti.
        /// </summary>
        public static string lblNavProducts {
            get {
                return ResourceManager.GetString("lblNavProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Non sei autorizzato a visualizzare le cateogorie di parametri.
        /// </summary>
        public static string lblNoAuth {
            get {
                return ResourceManager.GetString("lblNoAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Non ci sono categorie da visualizzare.
        /// </summary>
        public static string lblNoCategories {
            get {
                return ResourceManager.GetString("lblNoCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descrizione.
        /// </summary>
        public static string lblTHCatDescription {
            get {
                return ResourceManager.GetString("lblTHCatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nome.
        /// </summary>
        public static string lblTHCatName {
            get {
                return ResourceManager.GetString("lblTHCatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categorie di parametri di prodotto.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
    }
}
