//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResFreeMeasurements {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Execute {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Execute() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIS.Areas.FreeTimeMeasurement.Views.FreeMeasurement.App_LocalResources.Execute", typeof(Execute).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inizia un task NON produttivo.
        /// </summary>
        public static string lblChooseNoProductiveTask {
            get {
                return ResourceManager.GetString("lblChooseNoProductiveTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scegli l&apos;operatore.
        /// </summary>
        public static string lblChooseOperator {
            get {
                return ResourceManager.GetString("lblChooseOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inizia un task produttivo.
        /// </summary>
        public static string lblChooseProductiveTask {
            get {
                return ResourceManager.GetString("lblChooseProductiveTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hai superato il massimo numero di task avviabili. Metti in pausa o termina un task in esecuzione..
        /// </summary>
        public static string lblErrorStart4 {
            get {
                return ResourceManager.GetString("lblErrorStart4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devi selezionare solo uno fra task e nuovo task.
        /// </summary>
        public static string lblErrorStartOnlyOne {
            get {
                return ResourceManager.GetString("lblErrorStartOnlyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore: non esiste nessuna rilevazione configurata per questo reparto.
        /// </summary>
        public static string lblInputErrorMeasurement {
            get {
                return ResourceManager.GetString("lblInputErrorMeasurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rilievo / Prodotto.
        /// </summary>
        public static string lblMeasurementProduct {
            get {
                return ResourceManager.GetString("lblMeasurementProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task non in lista.
        /// </summary>
        public static string lblNewTask {
            get {
                return ResourceManager.GetString("lblNewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string lblNoProdTask {
            get {
                return ResourceManager.GetString("lblNoProdTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks in esecuzione.
        /// </summary>
        public static string lblRunningTasks {
            get {
                return ResourceManager.GetString("lblRunningTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string lblTask {
            get {
                return ResourceManager.GetString("lblTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fine.
        /// </summary>
        public static string lblTHEnd {
            get {
                return ResourceManager.GetString("lblTHEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rilievo.
        /// </summary>
        public static string lblTHMeasurementName {
            get {
                return ResourceManager.GetString("lblTHMeasurementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string lblTHNotes {
            get {
                return ResourceManager.GetString("lblTHNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pausa.
        /// </summary>
        public static string lblTHPause {
            get {
                return ResourceManager.GetString("lblTHPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantità.
        /// </summary>
        public static string lblTHQuantity {
            get {
                return ResourceManager.GetString("lblTHQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string lblTHTaskName {
            get {
                return ResourceManager.GetString("lblTHTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postazione.
        /// </summary>
        public static string lblTHWorkstation {
            get {
                return ResourceManager.GetString("lblTHWorkstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rilievo attività di lavoro.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore: task non riconosciuto.
        /// </summary>
        public static string lblUnknownTask {
            get {
                return ResourceManager.GetString("lblUnknownTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utente non autorizzato.
        /// </summary>
        public static string lblUserNotAuthorized {
            get {
                return ResourceManager.GetString("lblUserNotAuthorized", resourceCulture);
            }
        }
    }
}
