//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Shared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Shared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIS.Areas.Quality.Views.App_LocalResources.Shared", typeof(Shared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica azione correttiva.
        /// </summary>
        public static string lblNavCorrectiveAction {
            get {
                return ResourceManager.GetString("lblNavCorrectiveAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovo.
        /// </summary>
        public static string lblNavCreate {
            get {
                return ResourceManager.GetString("lblNavCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azione di miglioramento.
        /// </summary>
        public static string lblNavImprovementAction {
            get {
                return ResourceManager.GetString("lblNavImprovementAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azioni di miglioramento.
        /// </summary>
        public static string lblNavImprovementActions {
            get {
                return ResourceManager.GetString("lblNavImprovementActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cause di non conformità.
        /// </summary>
        public static string lblNavNCCauses {
            get {
                return ResourceManager.GetString("lblNavNCCauses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovo.
        /// </summary>
        public static string lblNavNCCausesNew {
            get {
                return ResourceManager.GetString("lblNavNCCausesNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica.
        /// </summary>
        public static string lblNavNCCausesUpd {
            get {
                return ResourceManager.GetString("lblNavNCCausesUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria di non conformità.
        /// </summary>
        public static string lblNavNCTypes {
            get {
                return ResourceManager.GetString("lblNavNCTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancella.
        /// </summary>
        public static string lblNavNCTypesDel {
            get {
                return ResourceManager.GetString("lblNavNCTypesDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuovo.
        /// </summary>
        public static string lblNavNCTypesNew {
            get {
                return ResourceManager.GetString("lblNavNCTypesNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica.
        /// </summary>
        public static string lblNavNCTypesUpd {
            get {
                return ResourceManager.GetString("lblNavNCTypesUpd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non conformità.
        /// </summary>
        public static string lblNavNonCompliances {
            get {
                return ResourceManager.GetString("lblNavNonCompliances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analisi non conformità.
        /// </summary>
        public static string lblNavNonCompliancesAnalysis {
            get {
                return ResourceManager.GetString("lblNavNonCompliancesAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analisi numero di non conformità.
        /// </summary>
        public static string lblNavNonCompliancesAnalysisNum {
            get {
                return ResourceManager.GetString("lblNavNonCompliancesAnalysisNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualità.
        /// </summary>
        public static string lblNavQuality {
            get {
                return ResourceManager.GetString("lblNavQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica.
        /// </summary>
        public static string lblNavUpdate {
            get {
                return ResourceManager.GetString("lblNavUpdate", resourceCulture);
            }
        }
    }
}
