//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResUsers {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WorkHoursManualRegistration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkHoursManualRegistration() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIS.Areas.Users.Views.Users.App_LocalResources.WorkHoursManualRegistration", typeof(WorkHoursManualRegistration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: non e possibile registrare la fine del task perche l&apos;utente non sta lavorando sul task..
        /// </summary>
        public static string lblAddErrCloseErrUserNotCurrentlyWorking {
            get {
                return ResourceManager.GetString("lblAddErrCloseErrUserNotCurrentlyWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: non si possono effettuare registrazioni manuali con data di fine futura..
        /// </summary>
        public static string lblAddErrFuture {
            get {
                return ResourceManager.GetString("lblAddErrFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore generico.
        /// </summary>
        public static string lblAddErrGeneric {
            get {
                return ResourceManager.GetString("lblAddErrGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore durante la registrazione nel database.
        /// </summary>
        public static string lblAddErrInsertInto {
            get {
                return ResourceManager.GetString("lblAddErrInsertInto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: non e possibile terminare il task perche ci sono alcuni parametri obbligatori..
        /// </summary>
        public static string lblAddErrParameters {
            get {
                return ResourceManager.GetString("lblAddErrParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: non tutti i task precedenti sono terminati..
        /// </summary>
        public static string lblAddErrPreviousTasks {
            get {
                return ResourceManager.GetString("lblAddErrPreviousTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: la data di inizio e posteriore a quella di fine.
        /// </summary>
        public static string lblAddErrStartPreviousThanEnd {
            get {
                return ResourceManager.GetString("lblAddErrStartPreviousThanEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: non e possibile aggiungere la registrazione perche e in conflitto con un altro intervallo di lavoro sullo stesso task!.
        /// </summary>
        public static string lblAddErrSuperposition {
            get {
                return ResourceManager.GetString("lblAddErrSuperposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: il task e gia chiuso.
        /// </summary>
        public static string lblAddErrTaskAlreadyClosed {
            get {
                return ResourceManager.GetString("lblAddErrTaskAlreadyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: task non trovato.
        /// </summary>
        public static string lblAddErrTaskNotFound {
            get {
                return ResourceManager.GetString("lblAddErrTaskNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: l&apos;utente attualmente sta lavorando sul task.
        /// </summary>
        public static string lblAddErrUserCurrentlyWorking {
            get {
                return ResourceManager.GetString("lblAddErrUserCurrentlyWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: l&apos;utente ha superato il numero massimo di task su cui puó lavorare contemporaneame.
        /// </summary>
        public static string lblAddErrUserMaxTasks {
            get {
                return ResourceManager.GetString("lblAddErrUserMaxTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: utente non autorizzato.
        /// </summary>
        public static string lblAddErrUserNotAuthorized {
            get {
                return ResourceManager.GetString("lblAddErrUserNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: utente non trovato.
        /// </summary>
        public static string lblAddErrUserNotFound {
            get {
                return ResourceManager.GetString("lblAddErrUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: l&apos;utente non ha effettuato l&apos;accesso alla postazione di lavoro.
        /// </summary>
        public static string lblAddErrUserNotLoggedInWorkstation {
            get {
                return ResourceManager.GetString("lblAddErrUserNotLoggedInWorkstation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aggiungi un intervallo di lavoro.
        /// </summary>
        public static string lblAddTimespan {
            get {
                return ResourceManager.GetString("lblAddTimespan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filtro cliente.
        /// </summary>
        public static string lblChooseCustomers {
            get {
                return ResourceManager.GetString("lblChooseCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scegli una data.
        /// </summary>
        public static string lblChooseDate {
            get {
                return ResourceManager.GetString("lblChooseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ordine.
        /// </summary>
        public static string lblChooseOrder {
            get {
                return ResourceManager.GetString("lblChooseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prodotto.
        /// </summary>
        public static string lblChooseProduct {
            get {
                return ResourceManager.GetString("lblChooseProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Task.
        /// </summary>
        public static string lblChooseTask {
            get {
                return ResourceManager.GetString("lblChooseTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data ed ora fine lavoro.
        /// </summary>
        public static string lblEndDateTime {
            get {
                return ResourceManager.GetString("lblEndDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: non si possono gestire orari di lavoro futuri.
        /// </summary>
        public static string lblErrorFutureDate {
            get {
                return ResourceManager.GetString("lblErrorFutureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: data non valida.
        /// </summary>
        public static string lblInvalidDate {
            get {
                return ResourceManager.GetString("lblInvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visualizza gli intervalli di lavoro registrati.
        /// </summary>
        public static string lblListTimespan {
            get {
                return ResourceManager.GetString("lblListTimespan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestione utenti.
        /// </summary>
        public static string lblNavManageUsers {
            get {
                return ResourceManager.GetString("lblNavManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: utente non autorizzato..
        /// </summary>
        public static string lblNoAuth {
            get {
                return ResourceManager.GetString("lblNoAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selezionare il task.
        /// </summary>
        public static string lblSelectTask {
            get {
                return ResourceManager.GetString("lblSelectTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Data ed ora inizio lavoro.
        /// </summary>
        public static string lblStartDateTime {
            get {
                return ResourceManager.GetString("lblStartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Task completato.
        /// </summary>
        public static string lblTaskCompleted {
            get {
                return ResourceManager.GetString("lblTaskCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrazione manuale orario di lavoro.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: operatore non trovato..
        /// </summary>
        public static string lblUserNotFound {
            get {
                return ResourceManager.GetString("lblUserNotFound", resourceCulture);
            }
        }
    }
}
