//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResNC {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FileUpload {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileUpload() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIS.Areas.Quality.Views.NonCompliances.App_LocalResources.FileUpload", typeof(FileUpload).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File non corretto o non conformità non trovata..
        /// </summary>
        public static string lblRes0 {
            get {
                return ResourceManager.GetString("lblRes0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File caricato correttamente.
        /// </summary>
        public static string lblRes1 {
            get {
                return ResourceManager.GetString("lblRes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esiste già un file con questo nome.
        /// </summary>
        public static string lblRes2 {
            get {
                return ResourceManager.GetString("lblRes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore generico.
        /// </summary>
        public static string lblRes3 {
            get {
                return ResourceManager.GetString("lblRes3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La dimensione del file è eccessiva oppure l&apos;estensione non è consentita..
        /// </summary>
        public static string lblRes4 {
            get {
                return ResourceManager.GetString("lblRes4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;estensione non è consentita. Estensioni consentite:.
        /// </summary>
        public static string lblRes5 {
            get {
                return ResourceManager.GetString("lblRes5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileUpload.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
    }
}
