//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResNC {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIS.Areas.Quality.Views.NonCompliances.App_LocalResources.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiungi una non conformità.
        /// </summary>
        public static string lblAdd {
            get {
                return ResourceManager.GetString("lblAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutti.
        /// </summary>
        public static string lblAll {
            get {
                return ResourceManager.GetString("lblAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chiuso.
        /// </summary>
        public static string lblClosed {
            get {
                return ResourceManager.GetString("lblClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data chiusura.
        /// </summary>
        public static string lblClosingDate {
            get {
                return ResourceManager.GetString("lblClosingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costo.
        /// </summary>
        public static string lblCost {
            get {
                return ResourceManager.GetString("lblCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore: non è stato possibile cancellare la non conformità.
        /// </summary>
        public static string lblDelError {
            get {
                return ResourceManager.GetString("lblDelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancella.
        /// </summary>
        public static string lblDelete {
            get {
                return ResourceManager.GetString("lblDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTENZIONE: stai per cancellare la non conformita.
        /// </summary>
        public static string lblDelWarn1 {
            get {
                return ResourceManager.GetString("lblDelWarn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perderai tutti i dati relativi a questa non conformita. Vuoi continuare?.
        /// </summary>
        public static string lblDelWarn2 {
            get {
                return ResourceManager.GetString("lblDelWarn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrizione.
        /// </summary>
        public static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID non conformità.
        /// </summary>
        public static string lblID {
            get {
                return ResourceManager.GetString("lblID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azione immediata.
        /// </summary>
        public static string lblImmediateAction {
            get {
                return ResourceManager.GetString("lblImmediateAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nessuna non conformità trovata..
        /// </summary>
        public static string lblNCNotFound {
            get {
                return ResourceManager.GetString("lblNCNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errore: non hai l&apos;autorizzazione necessaria per visualizzare le non conformità..
        /// </summary>
        public static string lblNotLoggedIn {
            get {
                return ResourceManager.GetString("lblNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperto.
        /// </summary>
        public static string lblOpen {
            get {
                return ResourceManager.GetString("lblOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data di apertura.
        /// </summary>
        public static string lblOpeningDate {
            get {
                return ResourceManager.GetString("lblOpeningDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stato.
        /// </summary>
        public static string lblStatus {
            get {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ricerca.
        /// </summary>
        public static string lblSubmit {
            get {
                return ResourceManager.GetString("lblSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non conformità.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggiorna.
        /// </summary>
        public static string lblUpdate {
            get {
                return ResourceManager.GetString("lblUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utente.
        /// </summary>
        public static string lblUser {
            get {
                return ResourceManager.GetString("lblUser", resourceCulture);
            }
        }
    }
}
