//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResNC {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Update {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Update() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIS.Areas.Quality.Views.NonCompliances.App_LocalResources.Update", typeof(Update).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aggiungi un prodotto selezionandolo da Warning Produzione.
        /// </summary>
        public static string lblAddProductByWarning {
            get {
                return ResourceManager.GetString("lblAddProductByWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aggiungi un prodotto selezionandolo dall&apos;elenco prodotti.
        /// </summary>
        public static string lblAddProductFromList {
            get {
                return ResourceManager.GetString("lblAddProductFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categorie della non conformità.
        /// </summary>
        public static string lblCategory {
            get {
                return ResourceManager.GetString("lblCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cause della non conformità.
        /// </summary>
        public static string lblCause {
            get {
                return ResourceManager.GetString("lblCause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chiuso.
        /// </summary>
        public static string lblClosed {
            get {
                return ResourceManager.GetString("lblClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo.
        /// </summary>
        public static string lblCost {
            get {
                return ResourceManager.GetString("lblCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: il costo inserito non ha un valore numerico..
        /// </summary>
        public static string lblCostNotNumeric {
            get {
                return ResourceManager.GetString("lblCostNotNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a €.
        /// </summary>
        public static string lblCurrency {
            get {
                return ResourceManager.GetString("lblCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descrizione.
        /// </summary>
        public static string lblDescription {
            get {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dettaglio della non conformità.
        /// </summary>
        public static string lblDetailNC {
            get {
                return ResourceManager.GetString("lblDetailNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: esiste già un file con questo nome.
        /// </summary>
        public static string lblErrFilename {
            get {
                return ResourceManager.GetString("lblErrFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: file non corretto o non conformità non trovata..
        /// </summary>
        public static string lblErrFileNCNotFound {
            get {
                return ResourceManager.GetString("lblErrFileNCNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: il file è troppo grande. Massima dimensione permessa: 20Mb.
        /// </summary>
        public static string lblErrFileSize {
            get {
                return ResourceManager.GetString("lblErrFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: tipo di file non permesso. File consentiti: .
        /// </summary>
        public static string lblErrFileTypeNotAllowed {
            get {
                return ResourceManager.GetString("lblErrFileTypeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: non conformità non trovata..
        /// </summary>
        public static string lblErrNCNotFound {
            get {
                return ResourceManager.GetString("lblErrNCNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore generico.
        /// </summary>
        public static string lblErrorGenerico {
            get {
                return ResourceManager.GetString("lblErrorGenerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File caricati.
        /// </summary>
        public static string lblFileList {
            get {
                return ResourceManager.GetString("lblFileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carica file.
        /// </summary>
        public static string lblFileUpload {
            get {
                return ResourceManager.GetString("lblFileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Azione immediata.
        /// </summary>
        public static string lblImmAction {
            get {
                return ResourceManager.GetString("lblImmAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prodotti coinvolti.
        /// </summary>
        public static string lblInvolvedProducts {
            get {
                return ResourceManager.GetString("lblInvolvedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prodotti coinvolti.
        /// </summary>
        public static string lblLinkedProducts {
            get {
                return ResourceManager.GetString("lblLinkedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Errore: non hai il permesso di modificare una non conformità.
        /// </summary>
        public static string lblNotLoggedIn {
            get {
                return ResourceManager.GetString("lblNotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aperto.
        /// </summary>
        public static string lblOpen {
            get {
                return ResourceManager.GetString("lblOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stato.
        /// </summary>
        public static string lblStato {
            get {
                return ResourceManager.GetString("lblStato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modifica non conformità.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modifica salvata correttamente..
        /// </summary>
        public static string lblUpdateOk {
            get {
                return ResourceManager.GetString("lblUpdateOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carica il file.
        /// </summary>
        public static string lblUpload {
            get {
                return ResourceManager.GetString("lblUpload", resourceCulture);
            }
        }
    }
}
