//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResGetGlobalKPIs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GetNonCompliancesKPIs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GetNonCompliancesKPIs() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KIS.Areas.Analysis.Views.GlobalKPIs.App_LocalResources.GetNonCompliancesKPIs", typeof(GetNonCompliancesKPIs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Non conformità attualmente aperte.
        /// </summary>
        public static string lblCurrentlyOpenedWarnings {
            get {
                return ResourceManager.GetString("lblCurrentlyOpenedWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Giorni.
        /// </summary>
        public static string lblDays {
            get {
                return ResourceManager.GetString("lblDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Non conformità.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Variazione.
        /// </summary>
        public static string lblVariation {
            get {
                return ResourceManager.GetString("lblVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Non conformità chiuse la scorsa settimana.
        /// </summary>
        public static string lblWarningClosedLastWeek {
            get {
                return ResourceManager.GetString("lblWarningClosedLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lead time scorsa settimana.
        /// </summary>
        public static string lblWarningClosedLastWeekLeadTime {
            get {
                return ResourceManager.GetString("lblWarningClosedLastWeekLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Non conformità chiuse questa settimana.
        /// </summary>
        public static string lblWarningClosedThisWeek {
            get {
                return ResourceManager.GetString("lblWarningClosedThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lead time settimana attuale.
        /// </summary>
        public static string lblWarningClosedThisWeekLeadTime {
            get {
                return ResourceManager.GetString("lblWarningClosedThisWeekLeadTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Non conformità aperte la scorsa settimana.
        /// </summary>
        public static string lblWarningOpenedLastWeek {
            get {
                return ResourceManager.GetString("lblWarningOpenedLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Non conformità aperte questa settimana.
        /// </summary>
        public static string lblWarningOpenedThisWeek {
            get {
                return ResourceManager.GetString("lblWarningOpenedThisWeek", resourceCulture);
            }
        }
    }
}
